---
apiVersion: v1
kind: Service
metadata:
  name: bind-secondary
  namespace: {{ .Release.Namespace }}
  {{- with .Values.primary.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: LoadBalancer
  loadBalancerIP: "{{ tpl (.Values.secondary.service.loadBalancerIP) . }}"
  externalTrafficPolicy: Cluster
  ports:
    - name: dns-tcp
      protocol: TCP
      port: 53
      targetPort: 53
    - name: dns-udp
      protocol: UDP
      port: 53
      targetPort: 53
  selector:
    app: bind-secondary

---
apiVersion: v1
kind: Service
metadata:
  name: bind-primary
  namespace: bind9
spec:
  type: ClusterIP
  clusterIP: "{{ .Values.bind9.primaryClusterIP }}"
  ports:
    - name: dns-tcp
      protocol: TCP
      port: 53
      targetPort: 53
    - name: dns-udp
      protocol: UDP
      port: 53
      targetPort: 53
  selector:
    app: bind-primary


