---
domain: ""
tsigKey: ""
zone:
  refresh: 10
  retry: 10
  expire: 3600
  negativeCacheTtl: 3600
  # passed through tpl
  dnsRecords: []

primary:
  service:
    # The bind9 primary (master) server needs to have a static ip, since 
    # /etc/bind/named.conf does not accept dns names in its "masters { <master-ip> };"
    # Make sure this value is within your kubernetes internal-ip range.
    clusterIP: "10.100.0.53"
  deployment:
    replicas: 1

secondary:
  service:
    loadBalancerIP: ""
  deployment:
    replicas: 4
