---
domain: ""
tsigKey: ""
zone:
  refresh: "10"
  retry: "10"
  expire: "1209600"
  negativeCacheTtl: "300"
  # passed through tpl
  dnsRecords: []

primary:
  annotations: {}
  service:
    # The bind9 primary (master) server needs to have a static ip, since 
    # /etc/bind/named.conf does not accept dns names in its "masters { <master-ip> };"
    # Make sure this value is within your kubernetes internal-ip range.
    clusterIP: "10.100.0.53"
  deployment:
    replicas: 1

secondary:
  annotations: {}
  service:
    loadBalancerIP: ""
  deployment:
    replicas: 4
